[package]
name = "duden-reference"
version = "0.1.0"
edition = "2024"

[dependencies]
colored = "3.0.0"
derive_more = { version = "2.0.1", features = ["debug", "display"] }
itertools = "0.14.0"
petgraph = { version = "0.8.3" }
rand = "0.9.2"
rayon = "1.11.0"
